server:
  port: 8095
  address: 0.0.0.0
  servlet:
    encoding:
      force: true

spring:
  main:
    allow-bean-definition-overriding: true
  application: nestco
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.220.247.78:3307/final_2405_team3
    username: final_2405_team3_user
    password: 1234

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 25643555405-rfc43ir1fs6bf56tiimop6g31mv21gil.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 3Fw8jEwUgQuw96dP4Wqm
            client-secret: ubZvp3sJzq
            scope:
              - name
              - email
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8092/login/oauth2/code/naver
          kakao:
            client-id: 4a69501b400932eb6c36e02a10047e50
            client-secret: dDFxWEGEfJ1K8Qm5TfrnEaYVmHLJZTVG
            scope:
              - profile_nickname
              #              - account_email
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8092/login/oauth2/code/kakao
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
coolsms:
  apikey:
  apisecret:
  fromnumber:

file:
  upload-dir: src/main/resources/static/uploads/thumbnails/