server:
  port: 9000
  servlet:
    encoding:
      force: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true50
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 450000

  sql:
    init:
      mode: always

  application:
    name: spring-react

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  #  h2:
  #    console:
  #      enabled: true

  #  datasource mySQL로 변경 필요

  #  datasource:
  #    driver-class-name: oracle.jdbc.OracleDriver
  #    url: jdbc:oracle:thin:@localhost:1521:orcl
  #    username: boarduser1
  #    password: 1234

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

coolsms:
  apikey:
  apisecret:
  fromnumber: